apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: {{CONTROL_NAMESPACE}}
  labels:
    app: cluster-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: {{REGISTRY}}/cluster-autoscaler:{{VERSION}}
          name: cluster-autoscaler
          env:
            - name: CONTROL_NAMESPACE
              value: /var/lib/configurations/control-namespace
            - name: CONTROL_KUBECONFIG
              value: /var/lib/configurations/control-kubeconfig
            - name: TARGET_KUBECONFIG
              value: /var/lib/configurations/target-kubeconfig
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --kubeconfig={{TARGET_KUBECONFIG}}
            - --cloud-provider=mcm
            - --nodes={{MIN}}:{{MAX}}:{{CONTROL_NAMESPACE}}.{{WORKER_POOL}}
            - --stderrthreshold=info
            - --scale-down-unneeded-time=10s
            - --skip-nodes-with-system-pods=false
            - --skip-nodes-with-local-storage=false
            - --scale-down-delay-after-add=10s
            - --scale-down-delay-after-failure=10s
            - --expander=least-waste
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - mountPath: /var/lib/configurations
              name: configurations
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs"
        - name: configurations
          secret:
            defaultMode: 420
            secretName: {{SECRET_NAME}}